name: "download crx"
on:
  workflow_dispatch:
    inputs:
      extensionId:
        description: '请填写chrome插件id'
        required: true
        default: 'gbldofcpkknbggpkmbdaefngejllnief'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: build
        uses: cardinalby/webext-buildtools-chrome-webstore-download-crx-action@v1.0.5
        with:
          extensionId: ${{ github.event.inputs.extensionId }}  
          crxFilePath: 'build/extension.published.crx'
