name: "download crx"


jobs:
  build:
    uses: cardinalby/webext-buildtools-chrome-webstore-download-crx-action@v1.0.5
    with:
      extensionId: 'gbldofcpkknbggpkmbdaefngejllnief'  
      crxFilePath: 'build/extension.published.crx'
