name: "download crx"
on:
  workflow_dispatch:
    inputs:
      extensionId:
        description: '请填写chrome插件id'
        required: true
        default: 'gbldofcpkknbggpkmbdaefngejllnief'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: prepare env
        run: |
          which python
          pip install playwright
          playwright install --with-deps chromium
          playwright install --with-deps chrome
        
      - name: get crx
        run: |
          # wget -O target.html "https://chromewebstore.google.com/detail/midscene/${{github.event.inputs.extensionId}}" >wtl.html
          ls -l
          pwd
          python play_chrome_store.py

      - name: zip
        run: |
          tar -czvf target.tar.gz dist/

      - name: release
        uses: softprops/action-gh-release@v2.1.0
        with:
          tag_name: target
          files: ${{ github.workspace }}/*.gz
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: build
      #   uses: cardinalby/webext-buildtools-chrome-webstore-download-crx-action@v1
      #   with:
      #     extensionId: ${{ github.event.inputs.extensionId }}  
      #     crxFilePath: 'build/extension.published.crx'
