name: "wget url"
on:
  workflow_dispatch:
    inputs:
      url:
        description: '请填写url'
        required: true
        default: 'https://chrome.google.com/webstore/category/extensions'

jobs:
  build_html:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: prepare env
      #   run: |
      #     which python
      #     pip install playwright
      #     playwright install --with-deps chromium
      #     playwright install --with-deps chrome
        
      - name: get html
        env:
          target_url: "${{github.event.inputs.url}}"
        run: |
          pwd
          env
          wget -O dist/target.html "${{github.event.inputs.url}}"
          env

      - name: zip
        run: |
          pwd
          tar -czvf target.tar.gz dist/

      - name: release
        uses: softprops/action-gh-release@v2.1.0
        with:
          tag_name: html_target
          files: ${{ github.workspace }}/*.gz
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
